--DROP DATABASE TCGStore;

--CREATE DATABASE TCGStore;
--GO
--USE TCGStore
DROP TABLE OrderItems;
DROP TABLE Inventory;
DROP TABLE SealedProduct;
DROP TABLE CardsInSet;
DROP TABLE [Set];
DROP TABLE Game;
DROP TABLE [Order];
DROP TABLE Customer;
DROP TABLE Administrator;

CREATE TABLE Administrator (
	AdminID INT NOT NULL IDENTITY(1,1),
	FirstName VARCHAR(15) NOT NULL,
	LastName VARCHAR(15) NOT NULL,
	[Password] VARCHAR(20) NOT NULL,
	Email VARCHAR(30) NOT NULL
);

ALTER TABLE Administrator
	ADD CONSTRAINT PK_AdminID PRIMARY KEY (AdminID);
ALTER TABLE Administrator
	ADD CONSTRAINT CK_AdminEmail CHECK (Email LIKE '%___@%___.%___');

CREATE TABLE Customer (
	CustomerID INT NOT NULL IDENTITY(10000000,1),
	FirstName VARCHAR(15) NOT NULL,
	LastName VARCHAR(15) NOT NULL,
	Password VARCHAR(20) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	Address VARCHAR(50) NULL,
	PostalCode VARCHAR(7) NULL,
	City VARCHAR(40) NULL,
	Province VARCHAR(25) NULL,
	PhoneNumber INT NULL
);

ALTER TABLE Customer
	ADD CONSTRAINT PK_CustomerID PRIMARY KEY (CustomerID);
ALTER TABLE Customer
	ADD CONSTRAINT CK_CustomerEmail CHECK (Email LIKE '%___@%___.%___');
ALTER TABLE Customer
	ADD CONSTRAINT CK_CustomerPostalCode CHECK (PostalCode LIKE '[A-Z][0-9][A-Z] [0-9][A-Z][0-9]');
ALTER TABLE Customer
	ADD CONSTRAINT CK_PhoneNumber CHECK (PhoneNumber LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')

CREATE TABLE Game (
	GameID INT NOT NULL IDENTITY (1,1),
	GameName VARCHAR(30) NOT NULL
);

ALTER TABLE Game
	ADD CONSTRAINT PK_Game PRIMARY KEY (GameID);

CREATE TABLE [Set] (
	SetID INT NOT NULL IDENTITY(60000000,1),
	SetCode VARCHAR(10) NOT NULL,
	GameID INT NOT NULL,
	SetName varchar(200) NOT NULL,	
	ReleaseDate DATE NOT NULL,
);

ALTER TABLE [Set]
	ADD CONSTRAINT PK_Set PRIMARY KEY (SetID);
ALTER TABLE [Set]
	ADD CONSTRAINT FK_GameID FOREIGN KEY(GameID) REFERENCES Game(GameID);

CREATE TABLE SealedProduct (
	SealedProductID INT NOT NULL IDENTITY(20000000,1),
	SetID INT NOT NULL,
	SealedProductName VARCHAR(150) NOT NULL
);

ALTER TABLE SealedProduct
	ADD CONSTRAINT PK_SealedProductID PRIMARY KEY (SealedProductID);
ALTER TABLE SealedProduct
	ADD CONSTRAINT FK_SealedProductSetID FOREIGN KEY(SetID) REFERENCES [Set](SetID);

----Identity increasee for MTG = 5, PKMN = 4
--CREATE TABLE YuGiOh (
--	YugiohID INT NOT NULL IDENTITY(30000000,1),
--	CardName VARCHAR(50) NOT NULL,
--	Description VARCHAR(1000) NOT NULL,
--	ATK INT NULL,
--	DEF INT NULL,
--	Level INT NULL,
--	Type VARCHAR(30),
--	Attribute VARCHAR(15),
--	CardType VARCHAR(15)
--);

--ALTER TABLE Yugioh
--	ADD CONSTRAINT PK_YugiohID PRIMARY KEY (YugiohID);

CREATE TABLE CardsInSet (
	CardID INT NOT NULL IDENTITY(1,1),
	SetID INT NOT NULL,
	CardCodeInSet VARCHAR(10) NOT NULL,
	CardName VARCHAR(75) NOT NULL,
	Rarity VARCHAR(75) NOT NULL,
	Price MONEY NOT NULL,
	ElementalType VARCHAR(25) NULL,
	SubType VARCHAR(25) NULL,
	SuperType VARCHAR(25) NULL,
	PictureLink VARCHAR(250) NULL,
	PictureSmallLink VARCHAR(250) NULL,
	APIImageID VARCHAR(15) NULL	
);

ALTER TABLE CardsInSet
	ADD CONSTRAINT FK_SetID FOREIGN KEY (SetID) REFERENCES [Set];
ALTER TABLE CardsInSet
	ADD CONSTRAINT PK_CardsInSet PRIMARY KEY (CardID);

CREATE TABLE Inventory (
	InventoryID INT NOT NULL IDENTITY(70000000,1),
	CardID INT NULL,
	SealedProductID INT NULL,
	Quantity INT NOT NULL,
	QualityID INT NOT NULL,
	FirstEdition BIT NULL
);

ALTER TABLE Inventory
	ADD CONSTRAINT PK_Inventory PRIMARY KEY (InventoryID);
ALTER TABLE Inventory
	ADD CONSTRAINT FK_CardID FOREIGN KEY(CardID) REFERENCES CardsInSet(CardID);
ALTER TABLE Inventory
	ADD CONSTRAINT FK_InventorySealedProductID FOREIGN KEY(SealedProductID) REFERENCES SealedProduct(SealedProductID);
ALTER TABLE Inventory
	ADD CONSTRAINT FK_QualityID FOREIGN KEY(QualityID) REFERENCES Quality(QualityID);

CREATE TABLE Quality (
	QualityID INT NOT NULL IDENTITY(1,1),
	QualityPercentage DECIMAL(5,2) NOT NULL,
	QualityName VARCHAR(25) NOT NULL,
	QualityShortName VARCHAR(2) NOT NULL
);

ALTER TABLE Quality
	ADD CONSTRAINT PK_QualityID PRIMARY KEY (QualityID);

CREATE TABLE [Order] (
	OrderID INT NOT NULL IDENTITY(80000000,1),
	CustomerID INT NOT NULL,
	AdminID INT NULL,
	ShippingType VARCHAR(15) NOT NULL,
	ShippingStatus VARCHAR(15) NULL,
	ShippingAddress VARCHAR(50) NOT NULL,
	ShippingPrice MONEY NULL,
	SaleDate DATE NOT NULL,
	UpdatedBy VARCHAR(20) NULL,
	SubTotal MONEY NOT NULL,
	PST MONEY NULL,
	HST MONEY NULL,
	GST MONEY NULL,
	Total MONEY NOT NULL,
);

ALTER TABLE [Order]
	ADD CONSTRAINT PK_OrderID PRIMARY KEY (OrderID);
ALTER TABLE [Order]
	ADD CONSTRAINT FK_OrderCustomerID FOREIGN KEY(CustomerID) REFERENCES Customer(CustomerID);
ALTER TABLE [Order]
	ADD CONSTRAINT FK_OrderAdminID FOREIGN KEY (AdminID) REFERENCES Administrator(AdminID);

CREATE TABLE OrderItems(
	OrderItemID INT NOT NULL IDENTITY(90000000,1),
	OrderID INT NOT NULL,
	InventoryID INT NULL,
	OrderQuantity INT NOT NULL,
	OrderItemPrice MONEY NOT NULL
);

ALTER TABLE OrderItems
	ADD CONSTRAINT PK_OrderItemID PRIMARY KEY (OrderItemID);
ALTER TABLE OrderItems
	ADD CONSTRAINT PK_OrderItemsOrderID FOREIGN KEY(OrderID) REFERENCES [Order](OrderID);
ALTER TABLE OrderItems
	ADD CONSTRAINT FK_OrderItemsInventory FOREIGN KEY(InventoryID) REFERENCES Inventory(InventoryID);

	SELECT * FROM Game
	SELECT * FROM [Set]
	SELECT * FROM CardsInSet
	DELETE FROM Game WHERE GameID = 1
	DELETE FROM [SET] WHERE GameID = 1