--DROP DATABASE TCGStore;

--CREATE DATABASE TCGStore;
--GO
--USE TCGStore
DROP TABLE OrderItems;
DROP TABLE Inventory;
DROP TABLE SealedProduct;
DROP TABLE CardsInSet;
DROP TABLE [Set];
DROP TABLE Game;
DROP TABLE [Order];
DROP TABLE Customer;
DROP TABLE Administrator;

CREATE TABLE Administrator (
	Email VARCHAR(30) NOT NULL,
	FirstName VARCHAR(15) NOT NULL,
	LastName VARCHAR(15) NOT NULL,
	[Password] VARCHAR(20) NOT NULL	
);

ALTER TABLE Administrator
	ADD CONSTRAINT PK_AdminEmail PRIMARY KEY (Email);
ALTER TABLE Administrator
	ADD CONSTRAINT CK_AdminEmail CHECK (Email LIKE '%___@%___.%___');

CREATE TABLE Customer (
	Email VARCHAR(30) NOT NULL,
	FirstName VARCHAR(15) NOT NULL,
	LastName VARCHAR(15) NOT NULL,
	Password VARCHAR(20) NOT NULL	
);

ALTER TABLE Customer
	ADD CONSTRAINT PK_CustomerEmail PRIMARY KEY (Email);
ALTER TABLE Customer
	ADD CONSTRAINT CK_CustomerEmail CHECK (Email LIKE '%___@%___.%___');

CREATE TABLE Game (
	GameID INT NOT NULL IDENTITY (1,1),
	GameName VARCHAR(30) NOT NULL
);

ALTER TABLE Game
	ADD CONSTRAINT PK_Game PRIMARY KEY (GameID);

CREATE TABLE [Set] (
	SetID INT NOT NULL IDENTITY(60000000,1),
	SetCode VARCHAR(10) NOT NULL,
	GameID INT NOT NULL,
	SetName varchar(200) NOT NULL,	
	ReleaseDate DATE NOT NULL,
);

ALTER TABLE [Set]
	ADD CONSTRAINT PK_Set PRIMARY KEY (SetID);
ALTER TABLE [Set]
	ADD CONSTRAINT FK_GameID FOREIGN KEY(GameID) REFERENCES Game(GameID);

CREATE TABLE SealedProduct (
	SealedProductID INT NOT NULL IDENTITY(20000000,1),
	SetID INT NOT NULL,
	SealedProductName VARCHAR(150) NOT NULL,
	Price MONEY NOT NULL
);

ALTER TABLE SealedProduct
	ADD CONSTRAINT PK_SealedProductID PRIMARY KEY (SealedProductID);
ALTER TABLE SealedProduct
	ADD CONSTRAINT FK_SealedProductSetID FOREIGN KEY(SetID) REFERENCES [Set](SetID);

CREATE TABLE CardsInSet (
	CardID INT NOT NULL IDENTITY(1,1),
	SetID INT NOT NULL,
	CardCodeInSet VARCHAR(10) NOT NULL,
	CardName VARCHAR(75) NOT NULL,
	Rarity VARCHAR(75) NOT NULL,
	Price MONEY NOT NULL,
	ElementalType VARCHAR(25) NULL,
	SubType VARCHAR(25) NULL,
	SuperType VARCHAR(25) NULL,
	PictureLink VARCHAR(250) NULL,
	PictureSmallLink VARCHAR(250) NULL,
	APIImageID VARCHAR(15) NULL	
);

ALTER TABLE CardsInSet
	ADD CONSTRAINT FK_SetID FOREIGN KEY (SetID) REFERENCES [Set];
ALTER TABLE CardsInSet
	ADD CONSTRAINT PK_CardsInSet PRIMARY KEY (CardID);

CREATE TABLE Inventory (
	InventoryID INT NOT NULL IDENTITY(70000000,1),
	CardID INT NULL,
	SealedProductID INT NULL,
	Quantity INT NOT NULL,
	QualityID INT NOT NULL,
	FirstEdition BIT NULL
);

ALTER TABLE Inventory
	ADD CONSTRAINT PK_Inventory PRIMARY KEY (InventoryID);
ALTER TABLE Inventory
	ADD CONSTRAINT FK_CardID FOREIGN KEY(CardID) REFERENCES CardsInSet(CardID);
ALTER TABLE Inventory
	ADD CONSTRAINT FK_InventorySealedProductID FOREIGN KEY(SealedProductID) REFERENCES SealedProduct(SealedProductID);
ALTER TABLE Inventory
	ADD CONSTRAINT FK_QualityID FOREIGN KEY(QualityID) REFERENCES Quality(QualityID);

CREATE TABLE Quality (
	QualityID INT NOT NULL IDENTITY(1,1),
	[Percentage] DECIMAL(5,2) NOT NULL,
	QualityName VARCHAR(25) NOT NULL,
	QualityShortName VARCHAR(2) NOT NULL
);

ALTER TABLE Quality
	ADD CONSTRAINT PK_QualityID PRIMARY KEY (QualityID);

CREATE TABLE [Order] (
	OrderID INT NOT NULL IDENTITY(80000000,1),
	CustomerID INT NOT NULL,
	AdminID INT NULL,
	ShippingID INT NOT NULL,
	StatusID INT NOT NULL,
	ShippingAddress VARCHAR(50) NOT NULL,
	PostalCode VARCHAR(7) NULL,
	City VARCHAR(40) NULL,
	Province VARCHAR(25) NULL,
	ShippingPrice MONEY NULL,
	SaleDate DATE NOT NULL,
	UpdatedBy VARCHAR(20) NULL,
	SubTotal MONEY NOT NULL,
	PST MONEY NULL,
	HST MONEY NULL,
	GST MONEY NULL,
	Total MONEY NOT NULL,
);

ALTER TABLE [Order]
	ADD CONSTRAINT PK_OrderID PRIMARY KEY (OrderID);
ALTER TABLE [Order]
	ADD CONSTRAINT FK_OrderCustomerID FOREIGN KEY(CustomerID) REFERENCES Customer(CustomerID);
ALTER TABLE [Order]
	ADD CONSTRAINT FK_OrderAdminID FOREIGN KEY (AdminID) REFERENCES Administrator(AdminID);
ALTER TABLE [Order]
	ADD CONSTRAINT FK_OrderShippingID FOREIGN KEY (ShippingID) REFERENCES Shipping(ShippingID);
ALTER TABLE [Order]
	ADD CONSTRAINT FK_OrderStatusID FOREIGN KEY (StatusID) REFERENCES [Status](StatusID);
ALTER TABLE [Order]
	ADD CONSTRAINT CK_OrderPostalCode CHECK (PostalCode LIKE '[A-Z][0-9][A-Z] [0-9][A-Z][0-9]');

CREATE TABLE OrderItems(
	OrderItemID INT NOT NULL IDENTITY(90000000,1),
	OrderID INT NOT NULL,
	InventoryID INT NULL,
	OrderQuantity INT NOT NULL,
	OrderItemPrice MONEY NOT NULL
);

ALTER TABLE OrderItems
	ADD CONSTRAINT PK_OrderItemID PRIMARY KEY (OrderItemID);
ALTER TABLE OrderItems
	ADD CONSTRAINT PK_OrderItemsOrderID FOREIGN KEY(OrderID) REFERENCES [Order](OrderID);
ALTER TABLE OrderItems
	ADD CONSTRAINT FK_OrderItemsInventory FOREIGN KEY(InventoryID) REFERENCES Inventory(InventoryID);

CREATE TABLE ShippingOptions
(
	ShippingID INT NOT NULL,
	ShippingName VARCHAR(30) NOT NULL
)

ALTER TABLE ShippingOptions
	ADD CONSTRAINT PK_ShippingID PRIMARY KEY (ShippingID);

CREATE TABLE ShippingStatus
(
	StatusID INT NOT NULL,
	StatusName VARCHAR(15) NOT NULL
)

ALTER TABLE ShippingStatus
	ADD CONSTRAINT PK_StatusID PRIMARY KEY (StatusID);
