--DROP DATABASE TCGStore;

CREATE DATABASE TCGStore;
GO
USE TCGStore

CREATE TABLE Administrator (
	AdminID INT NOT NULL IDENTITY(1,1),
	FirstName VARCHAR(15) NOT NULL,
	LastName VARCHAR(15) NOT NULL,
	[Password] VARCHAR(20) NOT NULL,
	Email VARCHAR(30) NOT NULL
);

ALTER TABLE Administrator
	ADD CONSTRAINT PK_AdminID PRIMARY KEY (AdminID);
ALTER TABLE Administrator
	ADD CONSTRAINT CK_AdminEmail CHECK (Email LIKE '%___@%___.%___');

CREATE TABLE Customer (
	CustomerID INT NOT NULL IDENTITY(1000,1),
	FirstName VARCHAR(15) NOT NULL,
	LastName VARCHAR(15) NOT NULL,
	[Password] VARCHAR(20) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	[Address] VARCHAR(50) NULL,
	PostalCode VARCHAR(7) NULL,
	City VARCHAR(40) NULL,
	Province VARCHAR(25) NULL,
	PhoneNumber INT NULL
);

ALTER TABLE Customer
	ADD CONSTRAINT PK_CustomerID PRIMARY KEY (CustomerID);
ALTER TABLE Customer
	ADD CONSTRAINT CK_CustomerEmail CHECK (Email LIKE '%___@%___.%___');
ALTER TABLE Customer
	ADD CONSTRAINT CK_CustomerPostalCode CHECK (PostalCode LIKE '[A-Z][0-9][A-Z] [0-9][A-Z][0-9]');
ALTER TABLE Customer
	ADD CONSTRAINT CK_PhoneNumber CHECK (PhoneNumber LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')

CREATE TABLE Game (
	GameID INT NOT NULL IDENTITY (1,1),
	GameName VARCHAR(30) NOT NULL
);

ALTER TABLE Game
	ADD CONSTRAINT PK_Game PRIMARY KEY (GameID);

CREATE TABLE [Set] (
	SetID INT NOT NULL IDENTITY(1, 1),
	GameID INT NOT NULL,
	SetName varchar(40) NOT NULL
);

ALTER TABLE [Set]
	ADD CONSTRAINT PK_Set PRIMARY KEY (SetID);
ALTER TABLE [Set]
	ADD CONSTRAINT FK_GameID FOREIGN KEY(GameID) REFERENCES Game(GameID);

CREATE TABLE SealedProduct (
	SealedProductID INT NOT NULL IDENTITY(1,1),
	SetID INT NOT NULL,
	SealedProductName VARCHAR(30) NOT NULL,
	Quantity INT NOT NULL,
	Price MONEY NOT NULL
);

ALTER TABLE SealedProduct
	ADD CONSTRAINT PK_SealedProductID PRIMARY KEY (SealedProductID);
ALTER TABLE SealedProduct
	ADD CONSTRAINT FK_SealedProductSetID FOREIGN KEY(SetID) REFERENCES [Set](SetID);

CREATE TABLE [Card] (
	CardID INT NOT NULL IDENTITY(1,1),
	SetID INT NOT NULL,
	CardName VARCHAR(50) NOT NULL,
	CardSetNumber VARCHAR(10) NOT NULL,
	CardRarity VARCHAR(20) NOT NULL,
	Quantity INT NOT NULL,
	CardPrice MONEY NOT NULL
);

ALTER TABLE [Card]
	ADD CONSTRAINT PK_CardID PRIMARY KEY (CardID);
ALTER TABLE [Card]
	ADD CONSTRAINT FK_CardSetID FOREIGN KEY(SetID) REFERENCES [Set](SetID);

CREATE TABLE [Order] (
	OrderID INT NOT NULL IDENTITY(300,1),
	CustomerID INT NOT NULL,
	AdminID INT NULL,
	ShippingType VARCHAR(15) NOT NULL,
	ShippingStatus VARCHAR(15) NULL,
	ShippingAddress VARCHAR(50) NOT NULL,
	SaleDate DATE NOT NULL,
	UpdatedBy VARCHAR(20) NULL,
	ShippingPrice MONEY NULL,
	SubTotal MONEY NOT NULL,
	PST MONEY NULL,
	HST MONEY NULL,
	GST MONEY NULL,
	Total MONEY NOT NULL,
);

ALTER TABLE [Order]
	ADD CONSTRAINT PK_OrderID PRIMARY KEY (OrderID);
ALTER TABLE [Order]
	ADD CONSTRAINT FK_OrderCustomerID FOREIGN KEY(CustomerID) REFERENCES Customer(CustomerID);
ALTER TABLE [Order]
	ADD CONSTRAINT FK_OrderAdminID FOREIGN KEY (AdminID) REFERENCES Administrator(AdminID);

CREATE TABLE OrderItems(
	OrderItemID INT NOT NULL IDENTITY(300,1),
	OrderID INT NOT NULL,
	SealedProductID INT NULL,
	CardID INT NULL,
	OrderQuantity INT NOT NULL,
	OrderItemPrice MONEY NOT NULL
);

ALTER TABLE OrderItems
	ADD CONSTRAINT PK_OrderItemID PRIMARY KEY (OrderItemID);
ALTER TABLE OrderItems
	ADD CONSTRAINT PK_OrderItemsOrderID FOREIGN KEY(OrderID) REFERENCES [Order](OrderID);
ALTER TABLE OrderItems
	ADD CONSTRAINT FK_OrderItemsSealedProductID FOREIGN KEY(SealedProductID) REFERENCES SealedProduct(SealedProductID);
ALTER TABLE OrderItems
	ADD CONSTRAINT FK_OrderItemsCardID FOREIGN KEY(CardID) REFERENCES [Card](CardID);
